name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4
      - run: haxe -version
      - name: Install External Dependencies
        run: |
          haxelib install hxcpp --quiet
          haxelib install format --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install emitter --quiet
          haxelib install flixel --quiet
          haxelib install haxeui-core --quiet
          haxelib install haxeui-flixel --quiet
      - name: Build Windows (64-Bit)
        run: haxelib run lime build $GITHUB_WORKSPACE windows
      - uses: actions/upload-artifact@v3
        with:
          name: Windows (64-Bit) Build
          path: D:/a/ludum-dare-56/ludum-dare-56/bin/windows/bin

  build-html5:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4
      - run: haxe -version
      - name: Install External Dependencies
        run: |
          haxelib install format --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install emitter --quiet
          haxelib install flixel --quiet
          haxelib install haxeui-core --quiet
          haxelib install haxeui-flixel --quiet
      - name: Build HTML5
        run: haxelib run lime build $GITHUB_WORKSPACE html5
      - uses: actions/upload-artifact@v3
        with:
          name: HTML5 Build
          path: D:/a/ludum-dare-56/ludum-dare-56/bin/html5/bin

  deploy-to-surge:
    runs-on: windows-latest
    needs: build-html5
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: HTML5 Build
          path: D:/a/ludum-dare-56/ludum-dare-56/bin/html5/bin
      - name: Deploy to Surge
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: haxecollab.ludum-dare-56.surge.sh
          project: D:/a/ludum-dare-56/ludum-dare-56/bin/html5/bin
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
